"""Initial migration

Revision ID: c93abd458272
Revises: 10676c6979aa
Create Date: 2018-06-23 15:05:38.513272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c93abd458272'
down_revision = '10676c6979aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('creater', sa.String(length=45), nullable=True),
    sa.Column('modified_time', sa.DATETIME(), nullable=True),
    sa.Column('modifier', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('creater', sa.String(length=45), nullable=True),
    sa.Column('modified_time', sa.DATETIME(), nullable=True),
    sa.Column('modifier', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('source_id', sa.String(length=45), nullable=True),
    sa.Column('action_name', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_actions',
    sa.Column('action_id', sa.String(length=45), nullable=True),
    sa.Column('role_id', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.drop_table('browse_volumes')
    op.add_column('article', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('article', sa.Column('creater', sa.String(length=45), nullable=True))
    op.add_column('article', sa.Column('modified_time', sa.DATETIME(), nullable=True))
    op.add_column('article', sa.Column('modifier', sa.String(length=45), nullable=True))
    op.add_column('article', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('article', 'update_time')
    op.drop_column('article', 'create_time')
    op.add_column('catalog', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('catalog', sa.Column('creater', sa.String(length=45), nullable=True))
    op.add_column('catalog', sa.Column('modified_time', sa.DATETIME(), nullable=True))
    op.add_column('catalog', sa.Column('modifier', sa.String(length=45), nullable=True))
    op.add_column('catalog', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('catalog', 'update_time')
    op.drop_column('catalog', 'create_time')
    op.add_column('comments', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('comments', sa.Column('creater', sa.String(length=45), nullable=True))
    op.add_column('comments', sa.Column('modified_time', sa.DATETIME(), nullable=True))
    op.add_column('comments', sa.Column('modifier', sa.String(length=45), nullable=True))
    op.add_column('comments', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('comments', 'update_time')
    op.drop_column('comments', 'create_time')
    op.add_column('mails', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('mails', sa.Column('creater', sa.String(length=45), nullable=True))
    op.add_column('mails', sa.Column('modified_time', sa.DATETIME(), nullable=True))
    op.add_column('mails', sa.Column('modifier', sa.String(length=45), nullable=True))
    op.add_column('mails', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('mails', 'update_time')
    op.drop_column('mails', 'create_time')
    op.add_column('posts', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('posts', sa.Column('creater', sa.String(length=45), nullable=True))
    op.add_column('posts', sa.Column('modified_time', sa.DATETIME(), nullable=True))
    op.add_column('posts', sa.Column('modifier', sa.String(length=45), nullable=True))
    op.add_column('posts', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('posts', 'update_time')
    op.drop_column('posts', 'create_time')
    op.add_column('posts_tags', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('roles', sa.Column('creater', sa.String(length=45), nullable=True))
    op.add_column('roles', sa.Column('modified_time', sa.DATETIME(), nullable=True))
    op.add_column('roles', sa.Column('modifier', sa.String(length=45), nullable=True))
    op.add_column('roles', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('roles', 'update_time')
    op.drop_column('roles', 'create_time')
    op.add_column('tags', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('tags', sa.Column('creater', sa.String(length=45), nullable=True))
    op.add_column('tags', sa.Column('modified_time', sa.DATETIME(), nullable=True))
    op.add_column('tags', sa.Column('modifier', sa.String(length=45), nullable=True))
    op.add_column('tags', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('tags', 'update_time')
    op.drop_column('tags', 'create_time')
    op.add_column('users', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('creater', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('modified_time', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('modifier', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('users', 'update_time')
    op.drop_column('users', 'create_time')
    op.add_column('users_roles', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_roles', 'status')
    op.add_column('users', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'status')
    op.drop_column('users', 'modifier')
    op.drop_column('users', 'modified_time')
    op.drop_column('users', 'creater')
    op.drop_column('users', 'created_time')
    op.add_column('tags', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('tags', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.drop_column('tags', 'status')
    op.drop_column('tags', 'modifier')
    op.drop_column('tags', 'modified_time')
    op.drop_column('tags', 'creater')
    op.drop_column('tags', 'created_time')
    op.add_column('roles', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('roles', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.drop_column('roles', 'status')
    op.drop_column('roles', 'modifier')
    op.drop_column('roles', 'modified_time')
    op.drop_column('roles', 'creater')
    op.drop_column('roles', 'created_time')
    op.drop_column('posts_tags', 'status')
    op.add_column('posts', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('posts', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'modifier')
    op.drop_column('posts', 'modified_time')
    op.drop_column('posts', 'creater')
    op.drop_column('posts', 'created_time')
    op.add_column('mails', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('mails', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.drop_column('mails', 'status')
    op.drop_column('mails', 'modifier')
    op.drop_column('mails', 'modified_time')
    op.drop_column('mails', 'creater')
    op.drop_column('mails', 'created_time')
    op.add_column('comments', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('comments', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.drop_column('comments', 'status')
    op.drop_column('comments', 'modifier')
    op.drop_column('comments', 'modified_time')
    op.drop_column('comments', 'creater')
    op.drop_column('comments', 'created_time')
    op.add_column('catalog', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('catalog', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.drop_column('catalog', 'status')
    op.drop_column('catalog', 'modifier')
    op.drop_column('catalog', 'modified_time')
    op.drop_column('catalog', 'creater')
    op.drop_column('catalog', 'created_time')
    op.add_column('article', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('article', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'status')
    op.drop_column('article', 'modifier')
    op.drop_column('article', 'modified_time')
    op.drop_column('article', 'creater')
    op.drop_column('article', 'created_time')
    op.create_table('browse_volumes',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('home_view_total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('roles_actions')
    op.drop_table('actions')
    op.drop_table('sources')
    # ### end Alembic commands ###
