"""Initial migration

Revision ID: d0d3041ada5a
Revises: c93abd458272
Create Date: 2018-06-23 15:12:15.507204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d3041ada5a'
down_revision = 'c93abd458272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('creater', sa.String(length=45), nullable=True),
    sa.Column('modified_time', sa.DATETIME(), nullable=True),
    sa.Column('modifier', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('action_name', sa.String(length=128), nullable=True),
    sa.Column('client_ip', sa.String(length=128), nullable=True),
    sa.Column('action_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attach_resources',
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('creater', sa.String(length=45), nullable=True),
    sa.Column('modified_time', sa.DATETIME(), nullable=True),
    sa.Column('modifier', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('attach_name', sa.String(length=255), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('belong_type', sa.String(length=45), nullable=True),
    sa.Column('belong_id', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('creater', sa.String(length=45), nullable=True),
    sa.Column('modified_time', sa.DATETIME(), nullable=True),
    sa.Column('modifier', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.String(length=45), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group')
    op.drop_table('attach_resources')
    op.drop_table('action_log')
    # ### end Alembic commands ###
